### ISSUE TITLE
SoftSPI?

### ISSUE THREAD

**Issue by clach04** [Carlo47/CYD_Basics#1]
From https://github.com/Carlo47/CYD_Basics/blob/638e8ab7bfd68cd93731ef6cd9b86fb2951932a6/README.md?plain=1#L12

From skimming the code of some of the lvgl (and micropython) code it looks like they use software SPI (slower) rather than hardware SPI, I think to allow reuse. I've not tested this out but thought it was worth sharing, just-in-case you'd not seen lvgl.

**Comment by clach04** [comment]
See https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/discussions/88

**Comment by Carlo47** [comment]
Thank you for your feedback. In the meantime I have also realized that only an additional SPI interface can solve the shortcomings of the CYD design. I came across nitek's software SPI solution (https://registry.platformio.org/libraries/nitek/XPT2046_Bitbang_Slim) and have largely adopted it for my applications where I have to operate all 3 SPI devices.
